882-fe-sso-create-table-dont-include-checkbox-and-icon-for-now
IT-Academy-BCN/ita-wiki pull request #1009
Opened 2024-02-23 15:55 UTC by marmorrei

Closes #882

2024-02-27 08:06 UTC, NataliaR-BCN commented on sso_front/src/components/organisms/UsersTable.tsx
> +  })
You should use styled-components

2024-02-27 08:06 UTC, NataliaR-BCN commented on sso_front/src/components/organisms/UsersTable.tsx
> +      <tbody>{userRows}</tbody>
userRows should be a component, maybe a molecule

2024-02-27 08:37 UTC, kevinmamaqi requested changes

2024-02-27 08:37 UTC, kevinmamaqi commented on sso_front/src/pages/Home.tsx
> +const mockUsers: TUser[] = [
Eliminar

2024-02-27 08:37 UTC, kevinmamaqi commented on sso_front/src/pages/Home.tsx
> +export type TUser = {
Eliminar

2024-02-27 08:37 UTC, kevinmamaqi commented on sso_front/src/pages/Home.tsx
> +export type TStatus = 'pendiente' | 'activo' | 'bloqueado'
Eliminar

2024-02-29 08:16 UTC, closed without merging

2024-02-29 08:16 UTC, marmorrei commented
Due tu restructuring of monorepo