Added Icon SelectGroup
IT-Academy-BCN/ita-wiki pull request #1025
Opened 2024-03-03 17:37 UTC by ursulacubilla

Closes #881

2024-03-04 07:40 UTC, kevinmamaqi requested changes
Falta crear el story, o actualizarlo para mostrar el icono

2024-03-07 08:04 UTC, kevinmamaqi requested changes

2024-03-07 08:04 UTC, kevinmamaqi commented on packages/ui/CHANGELOG.md
> +## [0.30.0] - 2024-02-27
Actualizar

2024-03-07 08:04 UTC, kevinmamaqi commented on packages/ui/src/components/atoms/Select.tsx
> +// const CustomOption = styled.option<TOption>`
Eliminar

2024-03-13 15:44 UTC, marmorrei commented on packages/ui/src/components/atoms/Dropdown.tsx
> +  icon?: string;
Estos props value y icon ya no son necesarios, los puedes borrar. En el array de options está incluido un icono y un valor para cada opción.

2024-03-13 15:47 UTC, marmorrei commented on packages/ui/src/stories/atoms/Dropdown/Dropdown.stories.tsx
> +    icon: { control: 'text'}
Este icon también se tendría que borrar, ya que se borra en el componente.

2024-03-13 15:50 UTC, marmorrei commented on packages/ui/src/stories/atoms/Dropdown/Dropdown.stories.tsx
> +    defaultValue: 'Option 2',
La defaultValue tiene que ser el id, que es lo que da el valor de cada opción, en vez del name

2024-03-13 16:50 UTC, NataliaR-BCN requested changes

2024-03-13 16:50 UTC, NataliaR-BCN commented on packages/ui/src/__tests__/atoms/Dropdown.test.tsx
>          <p>Test children content</p>
The dropdown does not need children anymore, use options instead (in all tests)

2024-03-13 16:50 UTC, NataliaR-BCN commented on packages/ui/src/components/atoms/Dropdown.tsx
You can delete both console.log we used for debugging

2024-03-19 10:38 UTC, NataliaR-BCN commented on packages/ui/src/__tests__/atoms/Dropdown.test.tsx
> +    expect(screen.queryByText('Test children content')).toBeVisible()
'Test children content' was text in children, you have to update it with some text in options

2024-03-19 10:44 UTC, marmorrei commented on packages/ui/src/__tests__/atoms/Dropdown.test.tsx
>      expect(screen.queryByText('Test children content')).not.toBeInTheDocument()
Aquí igual que en el anterior

2024-03-19 10:55 UTC, NataliaR-BCN commented on packages/ui/src/__tests__/atoms/Dropdown.test.tsx
>      expect(screen.queryByText('Test children content')).not.toBeInTheDocument()
Claro que 'Test children content' no está, hay que probar con un texto que podría estar, como te dice María

2024-03-20 08:06 UTC, kevinmamaqi submitted a review, later dismissed

2024-03-20 08:17 UTC, NataliaR-BCN commented on packages/ui/src/components/atoms/Dropdown.tsx
> +              title={isDropdownOpen ? openText : closeText}
Están los textos al revés: cuando el dropdown está abierto el texto invita a cerrar, y al revés

2024-03-20 14:49 UTC, NataliaR-BCN approved these changes

2024-03-21 07:25 UTC, marmorrei approved these changes

2024-03-21 08:01 UTC, merged