891 be sso implement blocked user status functionality
IT-Academy-BCN/ita-wiki pull request #1042
Opened 2024-03-05 20:19 UTC by MiguelKummetz

Ahora mismo creo que no hay diferencias entre 'Inactive' y 'Blocked'

ita-wiki\services\sso\src\controllers\auth\loginController.ts:
```
if (user.status !== UserStatus.ACTIVE) {
    throw new ForbiddenError('Only active users can login')
  }
```

debería separar este if en dos, uno para inactive y otro para blocked?
o añadir otro solo para blocked aunque ahora mismo sea redundante?

2024-03-06 07:55 UTC, kevinmamaqi requested changes
Parecen errores de prettier

2024-03-06 07:55 UTC, kevinmamaqi commented on config/dev/service_sso.yml
> +  version: 1.14.1
Este archivo no debe cambiar

2024-03-06 07:55 UTC, kevinmamaqi commented on services/sso/src/__tests__/auth/login.test.ts
> +      .post(route)
prettier.rc

2024-03-12 10:47 UTC, xpan1c approved these changes

2024-03-12 11:42 UTC, roche-tan submitted a review, later dismissed

2024-03-14 08:23 UTC, merged