Remove getResourcesTopic and consolidate it into resources/list
IT-Academy-BCN/ita-wiki pull request #1089
Opened 2024-03-19 19:00 UTC by roche-tan

2024-03-20 08:52 UTC, xpan1c requested changes

2024-03-20 08:52 UTC, xpan1c commented on services/wiki/src/__tests__/resources/list.test.ts
> +  // await prisma.topicsOnResources.deleteMany({
delete these comments

2024-03-20 08:52 UTC, xpan1c commented on services/wiki/tsconfig.json
> -  "include": ["src/**/*.ts"],
remove `src/__tests__/resources/byTopic.test.tst`

2024-03-20 08:52 UTC, xpan1c commented on services/wiki/src/controllers/resources/list.ts
> +
`topicId ` is handled in the query string

2024-03-21 08:02 UTC, kevinmamaqi approved these changes

2024-03-21 08:11 UTC, xpan1c approved these changes
this file should be deleted: `services\wiki\src\openapi\routes\resources\id.ts`

2024-03-21 09:04 UTC, merged