1129-be-sso-add-soft-delete
IT-Academy-BCN/ita-wiki pull request #1156
Opened 2024-04-15 07:00 UTC by MiguelKummetz

2024-04-16 07:04 UTC, kevinmamaqi requested changes

2024-04-16 07:04 UTC, kevinmamaqi commented on services/sso/CHANGELOG.md
> +## [1.19.0] - 2024-04-15
dejar espacio en blanco

2024-04-16 07:04 UTC, kevinmamaqi commented on services/sso/CHANGELOG.md
> +### Added
dejar espacio en blanco

2024-04-16 07:04 UTC, kevinmamaqi commented on services/sso/src/middleware/authenticate.ts
> +  const authToken = (ctx.request.body as ValidateSchema)?.authToken
```suggestion
  const authToken = ctx.request.body?.authToken
```

2024-04-16 09:31 UTC, xpan1c commented on services/sso/src/__tests__/dashboard/users/delete.test.ts
> +  it('should fail with no cokkies', async () => {
```suggestion
  it('should fail with no cookies', async () => {
```

2024-04-16 09:36 UTC, xpan1c requested changes

2024-04-16 09:36 UTC, xpan1c commented on services/sso/src/__tests__/dashboard/users/delete.test.ts
> +  it('should fail with no cokkies', async () => {
Spell check

2024-04-16 10:45 UTC, xpan1c commented on services/sso/src/openapi/routes/dashboard/users/delete.ts
> +  path: `${pathRoot.v1.dashboard.users}/:id`,
```suggestion
  path: `${pathRoot.v1.dashboard.users}/{id}`,
```

2024-04-16 10:48 UTC, xpan1c requested changes

2024-04-16 10:48 UTC, xpan1c commented on services/sso/src/openapi/routes/dashboard/users/delete.ts
> +  path: `${pathRoot.v1.dashboard.users}/:id`,
```suggestion
  path: `${pathRoot.v1.dashboard.users}/{id}`,
```

2024-04-16 10:48 UTC, xpan1c commented on services/sso/src/openapi/routes/dashboard/users/delete.ts
> +  responses: {
```typescript
request: {
    params: z.object({ id: userIdSchema }),
```

2024-04-16 11:05 UTC, xpan1c approved these changes

2024-04-17 06:48 UTC, julianamanzieri approved these changes

2024-04-17 07:27 UTC, kevinmamaqi approved these changes

2024-04-17 07:39 UTC, merged