1128 add patch endpoint
IT-Academy-BCN/ita-wiki pull request #1166
Opened 2024-04-15 14:49 UTC by julianamanzieri

2024-04-16 07:20 UTC, kevinmamaqi commented on services/sso/src/__tests__/dashboard/users/update.test.ts
> +  const response = await supertest(server)
Utilizar endpoint adecuado para crear

2024-04-16 07:20 UTC, kevinmamaqi commented on services/sso/src/__tests__/dashboard/users/update.test.ts
> +beforeAll(async () => {
Si creas un usuario, luego crear un afterAll para borrarlo

2024-04-17 08:34 UTC, MiguelKummetz submitted a review, later dismissed

2024-04-17 08:40 UTC, xpan1c requested changes

2024-04-17 08:40 UTC, xpan1c commented on services/sso/src/openapi/components/responses.ts
> +
```suggestion
```

2024-04-17 08:40 UTC, xpan1c commented on services/sso/src/openapi/components/responses.ts
> +
`userUpdateResponse` is currently not being used

2024-04-17 08:44 UTC, MiguelKummetz approved these changes

2024-04-17 08:46 UTC, merged