1167 Refactor soft deleted related querys
IT-Academy-BCN/ita-wiki pull request #1177
Opened 2024-04-18 00:19 UTC by MiguelKummetz

2024-04-18 13:38 UTC, xpan1c requested changes

2024-04-18 13:38 UTC, xpan1c commented on services/sso/src/__tests__/auth/login.test.ts
> +    ])
This should be in `afterAll`

2024-04-18 13:38 UTC, xpan1c commented on services/sso/src/__tests__/users/list.test.ts
> +    ])
This should be in `afterEach`

2024-04-18 13:38 UTC, xpan1c commented on services/sso/src/__tests__/users/list.test.ts
> +    ])
This should be in `afterEach`

2024-04-18 13:38 UTC, xpan1c commented on services/sso/src/controllers/users/list.ts
> +    `SELECT  ${fieldsToSelect} FROM "user" WHERE id IN (${queryParams}) AND deleted_at IS NULL`,
@kevinmamaqi service wiki doesn't implement soft deletes yet, should we remove this condition?

2024-04-23 06:56 UTC, xpan1c approved these changes

2024-04-23 09:48 UTC, julianamanzieri submitted a review, later dismissed

2024-04-24 07:02 UTC, julianamanzieri approved these changes

2024-04-24 07:02 UTC, merged