1187 add rol column and filter
IT-Academy-BCN/ita-wiki pull request #1211
Opened 2024-04-30 07:50 UTC by Xerxi88

2024-05-03 08:14 UTC, marmorrei commented on web/usuaris/src/__mocks__/handlers.ts
> +          role: UserRole,
Should it be here ```role: UserRole.ADMIN``` too?

2024-05-03 08:14 UTC, marmorrei commented on web/usuaris/src/components/organisms/FiltersWidget.tsx
> +  const handleRole = (role: TRol | undefined) => {
With the changes done in the qs you don't need to write the conditional, you should just put ```setFilters({ ...filters, role: role.slug })``` like in the handleItinerary

2024-05-03 08:15 UTC, marmorrei commented on web/usuaris/src/locales/en.json
> +  "mentor": "Mentor",
The keys here have to be the same in all 3 languages, otherwise it won't translate. In the catalan ones is "ADMIN", "REGISTERED" and "MENTOR"

2024-05-03 08:15 UTC, marmorrei commented on web/usuaris/src/locales/es.json
> +  "mentor": "Mentor",
Same as the previous one

2024-05-06 08:26 UTC, marmorrei approved these changes

2024-05-08 07:11 UTC, kevinmamaqi requested changes

2024-05-08 07:11 UTC, kevinmamaqi commented on web/usuaris/src/__tests__/hooks/useGetUsers.test.tsx
> +        role: 'ADMIN',
enums

2024-05-08 07:11 UTC, kevinmamaqi commented on web/usuaris/src/components/organisms/SideMenu.tsx
>    &[data-testid] {
Eliminar

2024-05-13 06:44 UTC, marmorrei commented on web/usuaris/src/components/organisms/SideMenu.tsx
> -    content: attr(data-testid);
These lines there is no need to touch them. You could undo the changes on this file to not appear in this pr

2024-05-13 08:04 UTC, merged