1196-be-sso-refactor-dashboarduserslist-query
IT-Academy-BCN/ita-wiki pull request #1215
Opened 2024-04-30 16:14 UTC by MiguelKummetz

2024-05-02 07:41 UTC, kevinmamaqi submitted a review, later dismissed

2024-05-06 07:36 UTC, xpan1c requested changes

2024-05-06 07:36 UTC, xpan1c commented on services/sso/src/__tests__/dashboard/users/list.test.ts
> +  })
These unit tests should be in a different file from the integration tests.

2024-05-06 09:50 UTC, xpan1c approved these changes

2024-05-06 10:04 UTC, joanbr4 approved these changes

2024-05-06 10:05 UTC, merged