sorted columns
IT-Academy-BCN/ita-wiki pull request #1263
Opened 2024-05-20 16:04 UTC by Xerxi88

2024-05-21 06:57 UTC, kevinmamaqi requested changes

2024-05-21 06:57 UTC, kevinmamaqi commented on web/usuaris/src/__tests__/molecules/Table.test.tsx
> +    fireEvent.click(screen.getByText('Nombre'))
pasar data-testid al header, usar getByTestId

2024-05-21 07:27 UTC, NataliaR-BCN commented on web/usuaris/src/components/molecules/Table.tsx
> +                  desc: <IconStyled src={icons.sortDown} />,
Include alt attribute in images

2024-05-21 13:29 UTC, marmorrei commented on web/usuaris/src/components/molecules/Table.tsx
> +import { IconStyled } from '../organisms/UsersTable/UsersTable.styles'
En lugar de importarlo podrías trasladar el styled component a este archivo porque no se utiliza más en UsersTable.tsx, si se pone aquí el icono.

2024-05-22 07:46 UTC, marmorrei approved these changes

2024-05-22 08:06 UTC, mllenas12 approved these changes

2024-05-22 09:39 UTC, merged