Fix radio buttons with defaultChecked
IT-Academy-BCN/ita-wiki pull request #1313
Opened 2024-05-29 14:14 UTC by Cristian-Moller

2024-05-30 07:17 UTC, kevinmamaqi requested changes

2024-05-30 07:17 UTC, kevinmamaqi commented on web/wiki/CHANGELOG.md
> +- Radio buttons defaultChecked
```suggestion
- Radio buttons defaultChecked

```

2024-06-06 08:59 UTC, mllenas12 approved these changes

2024-06-06 09:47 UTC, marmorrei approved these changes

2024-06-06 09:51 UTC, marmorrei submitted a review, later dismissed

2024-06-06 09:52 UTC, mllenas12 submitted a review, later dismissed

2024-06-10 07:24 UTC, kevinmamaqi approved these changes

2024-06-10 07:24 UTC, merged