1304-bewiki-remove-avatar-upload-middleware-from-wiki
IT-Academy-BCN/ita-wiki pull request #1373
Opened 2024-06-20 13:08 UTC by joanbr4

2024-06-21 14:35 UTC, xpan1c requested changes

2024-06-21 14:35 UTC, xpan1c commented on services/wiki/prisma/schema.prisma
The Prisma migration for the recent changes is missing

2024-06-25 08:49 UTC, xpan1c requested changes

2024-06-26 07:13 UTC, MiguelKummetz approved these changes

2024-06-26 07:16 UTC, xpan1c approved these changes

2024-06-26 16:55 UTC, merged