1397-be-sso-implement-knex-initial-config
IT-Academy-BCN/ita-wiki pull request #1398
Opened 2024-07-03 09:46 UTC by xpan1c

2024-07-03 10:18 UTC, joanbr4 approved these changes

2024-07-03 10:54 UTC, kevinmamaqi requested changes

2024-07-03 10:54 UTC, kevinmamaqi commented on services/sso/package.json
> +    "knex": "^3.1.0",
```suggestion
    "knex": "3.1.0",
```

2024-07-03 10:54 UTC, kevinmamaqi commented on services/sso/package.json
> +    "knex": "ts-node -r dotenv/config ./node_modules/knex/bin/cli.js --knexfile src/db/knexfile.ts"
```suggestion
    "db:migrate": "ts-node -r dotenv/config ./node_modules/knex/bin/cli.js --knexfile src/db/knexfile.ts"
```

2024-07-03 10:54 UTC, kevinmamaqi commented on services/sso/src/db/knexClient.ts
> +const config = configs[process.env.NODE_ENV || 'development']
Usa zod en un config, valida todo y que pete ahí antes de llegar a usar defaults, así si la variable no esta seteada peta antes. No obstante, para NODE_ENV la verdad que importa poco, siempre debería estarlo.

2024-07-03 10:54 UTC, kevinmamaqi commented on services/sso/src/db/knexfile.ts
> +      host: dbConfig.host || process.env.DB_HOST || 'localhost',
zod, debería estar ya validado

2024-07-03 14:51 UTC, joanbr4 approved these changes

2024-07-03 14:53 UTC, xpan1c commented on services/sso/package.json
> +    "knex": "ts-node -r dotenv/config ./node_modules/knex/bin/cli.js --knexfile src/db/knexfile.ts"
es el comando del cli, da pie a varios comandos:
- `npm run knex migrate:make migration_name` para crear una nueva migración
- `npm run knex migrate:latest` para levantar la última migración
- `npm run knex migrate:down` para deshacer la última migración 
- ... 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

2024-07-03 15:00 UTC, xpan1c commented on services/sso/src/config/index.ts
> +  knexClient: z.string(),
```suggestion
  nodeEnv: z.string(),
```

2024-07-03 15:00 UTC, xpan1c commented on services/sso/src/config/index.ts
> +  knexClient: process.env.NODE_ENV ?? 'development',
```suggestion
  nodeEnv: process.env.NODE_ENV ?? 'development',
```

2024-07-03 15:00 UTC, xpan1c commented on services/sso/src/db/knexClient.ts
> +const config = configs[dbConfig.knexClient]
```suggestion
const config = configs[dbConfig.nodeEnv]
```

2024-07-03 15:00 UTC, joanbr4 approved these changes

2024-07-04 13:30 UTC, solida29 approved these changes

2024-07-08 07:03 UTC, kevinmamaqi approved these changes

2024-07-08 07:04 UTC, merged