1402-besso-migrate-to-knex-post-authregister-endpoint
IT-Academy-BCN/ita-wiki pull request #1420
Opened 2024-07-17 15:35 UTC by solida29

2024-07-18 09:00 UTC, paula-uxengineer requested changes

2024-07-22 07:06 UTC, kevinmamaqi requested changes

2024-07-22 07:06 UTC, kevinmamaqi commented on services/sso/CHANGELOG.md
> +### [1.34.4] - 2024-07-17
```suggestion
### [1.35.0] - 2024-07-17
```

2024-07-22 07:06 UTC, kevinmamaqi commented on services/sso/package.json
> +  "version": "1.34.4",
```suggestion
  "version": "1.35.0",
```

2024-07-22 07:06 UTC, kevinmamaqi commented on services/sso/src/openapi/config.ts
> +    version: '1.34.4',
```suggestion
    version: '1.35.0',
```

2024-07-22 10:21 UTC, MiguelKummetz approved these changes

2024-07-22 10:29 UTC, kevinmamaqi approved these changes

2024-07-22 15:04 UTC, paula-uxengineer approved these changes

2024-07-22 15:45 UTC, merged