feat: migrate to knex getME endpoint and its tests.
IT-Academy-BCN/ita-wiki pull request #1428
Opened 2024-07-21 21:38 UTC by joanbr4

2024-07-22 06:19 UTC, solida29 submitted a review, later dismissed

2024-07-22 07:27 UTC, kevinmamaqi requested changes

2024-07-22 07:27 UTC, kevinmamaqi commented on services/sso/CHANGELOG.md
> +## [1.34.4] - 2024-07-21
```suggestion
## [1.35.0] - 2024-07-21
```

2024-07-22 11:09 UTC, solida29 approved these changes

2024-07-22 15:05 UTC, paula-uxengineer approved these changes

2024-07-22 21:01 UTC, solida29 approved these changes

2024-07-23 06:45 UTC, paula-uxengineer approved these changes

2024-07-23 07:00 UTC, kevinmamaqi approved these changes

2024-07-23 07:01 UTC, merged