1430 besso migrate to knex patch usersupdate endpoints
IT-Academy-BCN/ita-wiki pull request #1450
Opened 2024-07-24 22:53 UTC by joanbr4

2024-07-25 07:09 UTC, kevinmamaqi requested changes

2024-07-25 07:09 UTC, kevinmamaqi commented on services/sso/src/__tests__/users/update.test.ts
> +  const itineraryRows = await db('itinerary').select('id').limit(1)
Usar types

2024-07-25 12:10 UTC, solida29 commented on services/sso/src/db/managers/userManager.ts
> +  async updateUserByIds(options: UserPatch, ids: string[]): Promise<void> {
Me parece que falta el type
```async updateUserByIds<T extends keyof User>```

2024-07-25 12:14 UTC, solida29 requested changes
Falta el type en userManager

2024-07-28 22:06 UTC, solida29 approved these changes

2024-07-29 07:53 UTC, paula-uxengineer approved these changes

2024-07-29 09:16 UTC, solida29 approved these changes

2024-07-29 09:16 UTC, merged