1457-fewiki-replace-favMutation-in-favoritesIcon-component-with-corresponding-openapi-generated-fetcher
IT-Academy-BCN/ita-wiki pull request #1462
Opened 2024-07-29 17:00 UTC by Fanur1991

closes #1457

2024-07-30 07:11 UTC, kevinmamaqi requested changes

2024-07-30 07:11 UTC, kevinmamaqi commented on web/wiki/CHANGELOG.md
> +## [0.23.2] - 2024-07-29
```suggestion
## [0.23.0] - 2024-07-29
```

2024-07-30 07:11 UTC, kevinmamaqi commented on web/wiki/package.json
> +  "version": "0.23.2",
```suggestion
  "version": "0.23.0",
```

2024-07-31 09:48 UTC, Cristian-Moller submitted a review, later dismissed

2024-07-31 11:41 UTC, zookatt approved these changes

2024-07-31 11:43 UTC, Cristian-Moller approved these changes

2024-07-31 12:05 UTC, Fanur1991 commented on web/wiki/package.json
> +  "version": "0.23.2",
Changed

2024-07-31 17:47 UTC, Fanur1991 commented on web/wiki/CHANGELOG.md
> +## [0.23.2] - 2024-07-29
Changed

2024-09-16 07:12 UTC, merged