1432-besso-migrate-to-knex-get-dashboardusers-endpoints
IT-Academy-BCN/ita-wiki pull request #1465
Opened 2024-07-30 12:37 UTC by Aredhel269

2024-10-14 12:41 UTC, ghOdisea approved these changes
Merge first #1491 and after #1465. ChangeLog version changes.

2024-10-15 09:34 UTC, ClaudioMartinH requested changes

2024-10-15 09:34 UTC, ClaudioMartinH commented on services/sso/src/routes/dashboard/usersRoutes.ts
> +// import { dashboardUsersListQuerySchema } from '../../schemas'
borrar comentario

2024-10-15 09:34 UTC, ClaudioMartinH commented on services/sso/src/routes/dashboard/usersRoutes.ts
> +// REVISAR RUTA =>
eliminar comentario

2024-10-15 09:46 UTC, ClaudioMartinH approved these changes

2024-10-15 10:06 UTC, ghOdisea approved these changes

2024-10-15 10:51 UTC, ghOdisea approved these changes

2024-10-15 10:53 UTC, ClaudioMartinH approved these changes

2024-10-15 11:02 UTC, merged