[BE][SSO] Migrate to Knex ``DELETE dashboard/users`` endpoints
IT-Academy-BCN/ita-wiki pull request #1490
Opened 2024-10-03 07:06 UTC by Aredhel269

2024-10-08 07:01 UTC, ghOdisea submitted a review, later dismissed

2024-10-08 07:12 UTC, kevinmamaqi requested changes

2024-10-08 07:12 UTC, kevinmamaqi commented on services/sso/src/controllers/dashboard/users/batchDelete.ts
> +  // Verificar quins usuaris existeixen a la base de dades
Eliminar

2024-10-08 07:12 UTC, kevinmamaqi commented on services/sso/src/controllers/dashboard/users/batchDelete.ts
> +  // Filtrar els usuaris que no han estat esborrats
Eliminar

2024-10-08 07:12 UTC, kevinmamaqi commented on services/sso/src/controllers/dashboard/users/batchDelete.ts
> +  // Si hi ha usuaris per esborrar, actualitzar la seva columna 'deleted_at'
Eliminar

2024-10-08 07:12 UTC, kevinmamaqi commented on services/sso/src/controllers/dashboard/users/batchDelete.ts
> +  // Resposta 204: No Content, perquè no hi ha cos a la resposta
Eliminar

2024-10-09 07:06 UTC, kevinmamaqi approved these changes

2024-10-09 22:05 UTC, ghOdisea approved these changes

2024-10-10 07:31 UTC, merged