updated put Favourite by user id to knex methods
IT-Academy-BCN/ita-wiki pull request #1550
Opened 2024-10-30 07:28 UTC by ghOdisea

Also added cuid to generate testing id.

2024-10-30 08:33 UTC, Aredhel269 submitted a review, later dismissed

2024-10-30 09:35 UTC, ClaudioMartinH commented on services/wiki/src/__tests__/favorites/putFavoriteByUserId.test.ts
> +import { User } from '@prisma/client'
Remove User from prisma/client

2024-10-30 09:35 UTC, ClaudioMartinH requested changes
remove User import from prisma/client

2024-11-05 10:23 UTC, Aredhel269 commented on services/wiki/src/__tests__/favorites/putFavoriteByUserId.test.ts
> +    console.log('resource', resource)
remove  console.log

2024-11-06 09:29 UTC, ClaudioMartinH approved these changes

2024-11-07 14:53 UTC, merged