1572 bewiki create huggingface repository apiv1resourcesgenerate description endpoint and testing
IT-Academy-BCN/ita-wiki pull request #1573
Opened 2024-11-26 18:47 UTC by ClaudioMartinH

2024-11-27 06:22 UTC, kevinmamaqi-90poe requested changes

2024-11-27 06:22 UTC, kevinmamaqi-90poe commented on services/wiki/src/db/knexTypes.ts
> +export type TSupportedLanguage = 'en' | 'es' | 'ca'
Recomendación usar enums para tener validación en runtime:

```suggestion
export enum SupportedLanguage {
  English = 'en',
  Spanish = 'es',
  Catalan = 'ca',
}```

2024-11-27 06:22 UTC, kevinmamaqi-90poe commented on services/wiki/package.json
> +    "node-fetch": "^3.3.2",
```suggestion
    "node-fetch": "3.3.2",
```

2024-11-27 06:22 UTC, kevinmamaqi-90poe commented on services/wiki/src/controllers/resources/generateDescription.ts
> +    if (
¿Por qué no usar `zod`?

2024-11-27 06:22 UTC, kevinmamaqi-90poe commented on services/wiki/src/controllers/resources/generateDescription.ts
> +      ctx.status = 500
Quizas enviar el response.status que viene en lugar de aplicar un 500 por defecto

2024-11-27 06:22 UTC, kevinmamaqi-90poe commented on services/wiki/src/controllers/resources/generateDescription.ts
> +      message: 'An error occurred while getting the description',
Este mensaje debería ser el error, puede ocurrir fuera de cuando se obtiene la descripción

2024-12-04 08:04 UTC, kevinmamaqi requested changes

2024-12-04 08:04 UTC, kevinmamaqi commented on services/wiki/src/__tests__/itineraries/list.test.ts
> +const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))
```suggestion
```

2024-12-04 08:04 UTC, kevinmamaqi commented on services/wiki/src/__tests__/itineraries/list.test.ts
> +      await wait(1000)
```suggestion
```

2024-12-04 08:04 UTC, kevinmamaqi commented on services/wiki/src/__tests__/itineraries/list.test.ts
> +    { retry: 3 }
```suggestion
```

2024-12-09 10:25 UTC, kevinmamaqi approved these changes

2024-12-09 10:25 UTC, merged