152-fe-add-checkbox-component-to-register-form
IT-Academy-BCN/ita-wiki pull request #200
Opened 2023-04-25 18:30 UTC by NataliaR-BCN

He tenido que añadir el type JSX.Element a la Label para que acepte links

2023-04-25 19:20 UTC, kevinmamaqi requested changes

2023-04-25 19:20 UTC, kevinmamaqi commented on front/src/components/atoms/CheckBox.tsx
> +  label: string | JSX.Element
label debe ser un string

2023-04-25 19:20 UTC, kevinmamaqi commented on front/src/components/atoms/Label.tsx
> +  text: string | JSX.Element
Debe ser un string

2023-04-26 11:37 UTC, NataliaR-BCN commented
¡Cambios hechos!

2023-04-26 12:47 UTC, kevinmamaqi approved these changes

2023-04-26 12:47 UTC, kevinmamaqi commented on front/src/components/atoms/CheckBox.tsx
> +      className
```suggestion
      className = ""
```

2023-04-26 12:47 UTC, kevinmamaqi commented on front/src/components/atoms/CheckBox.tsx
> +    <Label htmlFor={id} text={label} hidden={hiddenLabel} />
```suggestion
        <Label htmlFor={id} text={label} hidden={hiddenLabel} />
```

2023-04-27 07:00 UTC, merged