190 be create new unique column slug on topics and resources
IT-Academy-BCN/ita-wiki pull request #201
Opened 2023-04-25 22:21 UTC by danimorera

2023-04-26 08:53 UTC, kevinmamaqi requested changes

2023-04-26 08:53 UTC, kevinmamaqi commented on back/prisma/schema.prisma
> +  slug         String?             @unique
Aquí debería ser requerido

2023-04-28 09:17 UTC, kevinmamaqi approved these changes

2023-04-28 09:40 UTC, danimorera commented
ya esta modificado, con 2 apuntes para otra issue necesaria:
-con el nuevo modelo fallaban 2 test de resources: 
----'should fail without topics': al fallar por no tener slug, devolvia estado 2xx, cuando al fallar, segun el controlador debe devolver 422, modificado el test para que espere 422 al fallar.
----should create a new resource with topics: fallaba por no recibir slug. modificado el test con slug hardcoded, pero se deberia modificar tanto el test como el controller para que el controller genere el slug.

2023-05-02 07:05 UTC, kevinmamaqi approved these changes

2023-05-02 07:05 UTC, merged