174 publish resources
IT-Academy-BCN/ita-wiki pull request #209
Opened 2023-05-02 06:25 UTC by Spanioulis

Closes #174

2023-05-02 06:29 UTC, Spanioulis commented
En principio los datos se "envían" correctamente (en tipo), pero la cuestión, entiendo, es que la Cookie ha de ser dinámica y se ha de obtener de algún lugar.

![resource_form](https://user-images.githubusercontent.com/97700906/235594347-7bb32f72-bf0c-47ec-abc6-d217d042febf.PNG)

2023-06-26 05:38 UTC, kevinmamaqi requested changes

2023-06-26 05:38 UTC, kevinmamaqi commented on front/src/__tests__/organisms/ResourceForm.test.tsx
>  import { fireEvent, render, screen, waitFor } from '@testing-library/react'
Importar desde test-utils

2023-06-26 05:38 UTC, kevinmamaqi commented on front/src/__tests__/organisms/ResourceForm.test.tsx
> +import { QueryClientProvider, QueryClient } from '@tanstack/react-query'
Una vez importas desde test-utils, puedes quitarlo

2023-06-26 05:38 UTC, kevinmamaqi commented on front/src/__tests__/organisms/ResourceForm.test.tsx
>    it('should show error message when form input is invalid', async () => {
Falta un test, en el cual completas todos los campos, envias y devuelve un response 200, y otro estaria bien donde devuelve un error la API.

2023-06-27 08:05 UTC, merged