177 vote counter
IT-Academy-BCN/ita-wiki pull request #213
Opened 2023-05-03 21:52 UTC by Lahali

2023-05-09 05:42 UTC, kevinmamaqi requested changes

2023-05-09 05:42 UTC, kevinmamaqi commented on front/package.json
> +    "cross-fetch": "^3.1.5",
Elimina la dependencia, creo que ya no hace falta.

2023-05-09 10:52 UTC, Lahali commented on front/package.json
> +    "cross-fetch": "^3.1.5",
En el package.json no me sale esa dependencia, me sale en el package-lock.json, ¿la elimino también de ahí?

2023-05-09 10:57 UTC, kevinmamaqi commented
No, haz un install y debería de irse si no está en el package.json

On Tue, 9 May 2023 at 12:53 Halimeh ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In front/package.json
> <https://github.com/IT-Academy-BCN/ita-wiki/pull/213#discussion_r1188480587>
> :
>
> > @@ -33,7 +33,7 @@
>      ***@***.***/parser": "5.55.0",
>      ***@***.***/plugin-react-swc": "^3.0.0",
>      ***@***.***/coverage-c8": "0.30.1",
> -    "cross-fetch": "3.1.5",
> +    "cross-fetch": "^3.1.5",
>
> En el package.json no me sale esa dependencia, me sale en el
> package-lock.json, ¿la elimino también de ahí?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IT-Academy-BCN/ita-wiki/pull/213#discussion_r1188480587>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHNO6DLD5I5CCP6CMJ56J3XFIOYZANCNFSM6AAAAAAXU7IUBA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-05-09 21:31 UTC, kevinmamaqi requested changes

2023-05-09 21:31 UTC, kevinmamaqi commented on front/src/__tests__/molecules/VoteCounter.test.tsx
> +import { render, screen, waitFor } from '@testing-library/react'
Utiliza el render de test-utils.tsx

2023-05-09 21:31 UTC, kevinmamaqi commented on front/src/__tests__/molecules/VoteCounter.test.tsx
> +      <QueryClientProvider client={queryClient}>
No es necesario

2023-05-09 21:31 UTC, kevinmamaqi commented on front/src/__tests__/molecules/VoteCounter.test.tsx
> +    mswServer.use(...voteHandlers)
Esto solo sirve en caso de querer mostrar un error.

2023-05-09 21:31 UTC, kevinmamaqi commented on front/src/components/molecules/VoteCounter.tsx
> +  const res = await fetch(url)
Falta gestionar el error

2023-05-09 21:31 UTC, kevinmamaqi commented on front/src/__mocks__/handlers.ts
> +export const voteHandlers = [
Si este se supone que da una respuesta correcta, introducelo en el array principal.

2023-05-11 07:09 UTC, kevinmamaqi requested changes

2023-05-11 07:09 UTC, kevinmamaqi commented on front/src/constants/urls.ts
> +  vote: '/api/v1/resources/vote/:resourceId/:vote'
Actualizar url @oriolsastre @Lahali

2023-05-11 07:09 UTC, kevinmamaqi commented on front/src/components/molecules/VoteCounter.tsx
> +const fetcher = async (resourceId: string, voteValue: string) => {
Hacer que sea un PUT

2023-05-11 07:09 UTC, kevinmamaqi commented on front/src/__tests__/molecules/VoteCounter.test.tsx
> +describe('Vote counter molecule', () => {
Testear clicks

2023-05-15 08:24 UTC, merged