189-fe-search-resources-by-title
IT-Academy-BCN/ita-wiki pull request #220
Opened 2023-05-08 16:56 UTC by llopFilms

Primera aproximació a filtratge de recursos a Home

2023-05-08 17:15 UTC, llopFilms commented
Falta el test

2023-05-10 15:03 UTC, llopFilms commented
Tenim un 'any' a TObjectWithTitle a 'useSearch', per això salta l'avís de ESLint. Crec que la resta està ok.

2023-05-10 15:56 UTC, llopFilms commented
Afegida excepció de tipatge 'any' a useSearch

2023-05-11 07:16 UTC, kevinmamaqi requested changes
Falta un intento de test

2023-05-11 07:16 UTC, kevinmamaqi commented on front/src/components/molecules/InputGroup.tsx
> +  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void
onChange no es necesario, ya esta en TInput

2023-05-11 08:23 UTC, llopFilms commented on front/src/components/molecules/InputGroup.tsx
> +  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void
Ja està tret

2023-05-17 08:00 UTC, llopFilms commented
Fets els canvis de 'id' per 'key'

2023-05-17 08:15 UTC, llopFilms commented
Faltava fegir 'key' als maps de Resource i ResourceList. Veig que ara està ok.

2023-05-17 08:18 UTC, kevinmamaqi approved these changes

2023-05-17 08:47 UTC, merged