264 fe get topics when navigating to a category
IT-Academy-BCN/ita-wiki pull request #291
Opened 2023-06-13 10:39 UTC by NataliaR-BCN

2023-06-14 11:28 UTC, kevinmamaqi requested changes

2023-06-14 11:28 UTC, kevinmamaqi commented on front/src/__tests__/organisms/CategoriesList.test.tsx
> +  it.skip('changes the url path when clicking a category', async () => {
... ¿Por qué skip?

2023-06-14 14:22 UTC, NataliaR-BCN commented on front/src/__tests__/organisms/CategoriesList.test.tsx
> +  it.skip('changes the url path when clicking a category', async () => {
Te lo comentaba más arriba: he detectado que este test ha dejado de funcionar. Supongo que es un daño colateral al cambiar los test-utils, ya que testea un cambio de url al navegar. No he sabido retocarlo para adaptarlo, y en vez de borrarlo directamente lo omito para que no falle, por si lo quieres revisar. 
¿Qué quieres que haga con él?

2023-06-19 07:06 UTC, kevinmamaqi approved these changes

2023-06-19 07:06 UTC, merged