302-fe-add-status-filter-widget-frontend-new
IT-Academy-BCN/ita-wiki pull request #303
Opened 2023-06-21 17:27 UTC by NataliaR-BCN

2023-06-21 17:35 UTC, NataliaR-BCN commented
Replaces [#250 ](https://github.com/IT-Academy-BCN/ita-wiki/issues/250)

2023-06-22 07:10 UTC, kevinmamaqi requested changes

2023-06-22 07:10 UTC, kevinmamaqi commented on front/src/__tests__/molecules/StatusFilterWidget.test.tsx
> +    screen.debug()
Eliminar

2023-06-22 07:10 UTC, kevinmamaqi commented on front/src/__tests__/molecules/StatusFilterWidget.test.tsx
> +  it('renders all checkboxes checked by default and user can uncheck them', async () => {
Ya se testea el click en el componente CheckBox

2023-06-22 07:10 UTC, kevinmamaqi commented on front/src/components/molecules/StatusFilterWidget.tsx
> +const StatusFilterWidget: FC = () => (
Falta recibir un callback para pasar los seleccionados al componente padre.

2023-06-26 05:41 UTC, kevinmamaqi approved these changes
Seguramente necesite ajustes cuando este todo completo, pero por el momento approved.

2023-06-26 07:13 UTC, merged