384 change sort order for resources
IT-Academy-BCN/ita-wiki pull request #390
Opened 2023-07-11 08:49 UTC by ViuCoding

2023-07-11 10:24 UTC, kevinmamaqi requested changes
Me parece poco reutilizable

2023-07-11 10:24 UTC, kevinmamaqi commented on front/src/hooks/useSortByDate.tsx
> +type TTopic = {
type SortOrder = 'asc' | 'desc'

2023-07-11 10:24 UTC, kevinmamaqi commented on front/src/hooks/useSortByDate.tsx
> +  sortOrder: 'ascending' | 'descending' = 'descending'
sortOrder: SortOrder = 'desc'

2023-07-11 10:24 UTC, kevinmamaqi commented on front/src/hooks/useSortByDate.tsx
> +export type TResource = {
Eliminar type TResource es demasiado especifico

2023-07-11 10:24 UTC, kevinmamaqi commented on front/src/hooks/useSortByDate.tsx
> +export const useSortByDate = (
export const useSortByDate = <T extends object>(
  items: T[] | undefined,
  sortBy: keyof T,

2023-07-12 07:40 UTC, kevinmamaqi requested changes

2023-07-12 07:40 UTC, kevinmamaqi commented on front/src/hooks/useSortByDate.tsx
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
```suggestion

```

2023-07-12 07:40 UTC, kevinmamaqi commented on front/src/hooks/useSortByDate.tsx
> +export const useSortByDate = <T extends Record<string, any>>(
```suggestion
export const useSortByDate = <T extends Record<string, unknown>>(
```

2023-07-12 07:45 UTC, ViuCoding commented on front/src/hooks/useSortByDate.tsx
> +export const useSortByDate = <T extends Record<string, any>>(
Hostras, sorry, arreglado, he abusado del "quick fix" =|

2023-07-12 07:57 UTC, kevinmamaqi approved these changes

2023-07-12 07:59 UTC, merged