add checking access by roles to authMiddleware
IT-Academy-BCN/ita-wiki pull request #391
Opened 2023-07-11 11:31 UTC by versalitas

I've tested the middleware briefly (admin and user) on the authMe endpoint. (I've not included the testing in the commit since not being executed on a pertinent endpoint)

2023-07-11 14:21 UTC, kevinmamaqi requested changes
Aunque en un principio he mencionado de introducirlo dentro del auth middleware, creo que era mejor tu approach de tenerlo fuera y separar autenticación de autorización. ¿Puedes meterlo en un authorization middleware por favor?

1. El que tenemos ahora se pasaria a llamar authentication
2. El nuevo pasaría a llamarse authorization (no hace falta que tenga el Middleware detras

2023-07-11 14:21 UTC, kevinmamaqi commented on back/src/middleware/authMiddleware.ts
> +    try {
Podemos quitar el try catch y usar el errorMiddleware

2023-07-11 14:21 UTC, kevinmamaqi commented on back/src/middleware/authMiddleware.ts
> +const checkRoleAccess = (requieredRole: USER_ROLE, userRole: USER_ROLE) => {
Esta función debería testearse

2023-07-14 09:36 UTC, kevinmamaqi approved these changes
Buen trabajo

2023-07-14 10:54 UTC, kevinmamaqi commented
Has incluido archivos de front.

2023-07-14 11:50 UTC, versalitas commented
> Has incluido archivos de front.

No sé qué estoy haciendo diferente de otras veces...

2023-07-14 17:51 UTC, closed without merging