navbar
IT-Academy-BCN/ita-wiki pull request #397
Opened 2023-07-12 07:10 UTC by MarcMorado

Falta hacer alguno test más en el UserButton.test.tsx, para comprobar el dropdownMenu y el Modal

2023-07-12 07:32 UTC, kevinmamaqi commented
El nombre del PR debe contener información relevante del issue. Similar al nombre de la rama

2023-07-12 08:40 UTC, kevinmamaqi requested changes

2023-07-12 08:40 UTC, kevinmamaqi commented on front/src/__tests__/molecules/UserButton.test.tsx
> +  it('should open dropdownMenu', () => {
???

2023-07-12 08:40 UTC, kevinmamaqi commented on front/src/components/molecules/UserButton.tsx
> +  const handleOutsideClick = (event: MouseEvent) => {
No se puede reutilizar el componente dropdown que ya tenemos?

2023-07-12 08:41 UTC, MarcMorado commented on front/src/__tests__/molecules/UserButton.test.tsx
> +  it('should open dropdownMenu', () => {
Este es el que decía que lo estaba haciendo, que no sabía como comprobar en los tests

2023-07-12 08:42 UTC, MarcMorado commented on front/src/components/molecules/UserButton.tsx
> +  const handleOutsideClick = (event: MouseEvent) => {
Este es el que estaba antes en el navbar, lo he reutilizado

2023-07-12 08:43 UTC, kevinmamaqi commented on front/src/__tests__/molecules/UserButton.test.tsx
> +  it('should open dropdownMenu', () => {
UserEventClick?

2023-07-12 08:44 UTC, MarcMorado commented on front/src/__tests__/molecules/UserButton.test.tsx
> +  it('should open dropdownMenu', () => {
Ahora lo miro! 👍

2023-07-12 08:44 UTC, kevinmamaqi commented on front/src/components/molecules/UserButton.tsx
> +  const handleOutsideClick = (event: MouseEvent) => {
Esta copiado, no reutilizado.

2023-07-12 08:46 UTC, MarcMorado commented on front/src/components/molecules/UserButton.tsx
> +  const handleOutsideClick = (event: MouseEvent) => {
Entonces uso mejor el que esta hecho en atoms?

2023-07-12 09:56 UTC, kevinmamaqi commented on front/src/components/molecules/UserButton.tsx
> +  const handleOutsideClick = (event: MouseEvent) => {
Si

2023-07-13 07:04 UTC, kevinmamaqi commented on front/src/__tests__/organisms/CategoriesList.test.tsx
> +    // await waitFor(() => {
Eliminar

2023-07-13 07:06 UTC, kevinmamaqi commented on front/src/__tests__/organisms/Navbar.test.tsx
> +    const settingsButton = screen.getByTestId('settingsImage1')
nombre más identificable

2023-07-13 07:07 UTC, kevinmamaqi commented on front/src/components/organisms/CategoriesList.tsx
> +        {/* <CategoriesListStyled align="stretch">
Elimina código comentado

2023-07-13 07:08 UTC, kevinmamaqi commented on front/src/components/organisms/Navbar.tsx
> +import UserButton from '../molecules/UserButton'
```suggestion
import { LanguageSelector, UserButton } from '../molecules'
```

2023-07-13 07:08 UTC, kevinmamaqi commented on front/src/components/organisms/Navbar.tsx
> +import LanguageSelector from '../molecules/SelectLanguage'
```suggestion
```

2023-07-17 07:01 UTC, kevinmamaqi requested changes
Al probar el menú desde mobile, no se cierra, además queda un hueco muy grande en la parte superior (video)

https://github.com/IT-Academy-BCN/ita-wiki/assets/972664/3f686d2e-7945-4dc1-9ec8-e4274f22a039

2023-07-17 07:01 UTC, kevinmamaqi commented on front/src/components/organisms/Navbar.tsx
> +// eslint-disable-next-line import/no-cycle
Eliminar no-cycle

2023-07-17 07:01 UTC, kevinmamaqi commented on front/src/components/organisms/Navbar.tsx
> +import { LanguageSelector, UserButton } from '../molecules'
Si usas LanguageSelector, llamar igual el archivo.

2023-07-17 08:32 UTC, merged