373-update-validation-form
IT-Academy-BCN/ita-wiki pull request #405
Opened 2023-07-13 00:00 UTC by jordilop

2023-07-18 05:12 UTC, kevinmamaqi approved these changes

2023-07-18 05:16 UTC, kevinmamaqi requested changes

2023-07-18 05:16 UTC, kevinmamaqi commented on front/src/components/organisms/Register.tsx
> +    await axios
Mover a `react-query` y testear exito/error. Reducir el número de `useState`

2023-07-18 05:16 UTC, kevinmamaqi commented on front/src/components/organisms/Register.tsx
> +  const categories = [
Deberían cargarse dinámicamente de la DB

2023-07-19 10:56 UTC, kevinmamaqi requested changes

2023-07-19 10:56 UTC, kevinmamaqi commented on front/src/__tests__/organisms/MyResources.test.tsx
> +    render(<MyResources categories={[]} />)
Porqué ?

2023-07-19 10:56 UTC, kevinmamaqi commented on front/src/components/organisms/CategoriesList.tsx
>    const { isLoading, data, error } = useQuery({
Añade el type del return aquí

2023-07-19 10:56 UTC, kevinmamaqi commented on front/src/components/organisms/MyFavoritesList.tsx
> +            categories={categories as TCategory[]}
Esto mejor pedirlo en register antes que pasarlo múltiples niveles

2023-07-19 16:03 UTC, jordilop commented on front/src/components/organisms/MyFavoritesList.tsx
> +            categories={categories as TCategory[]}
Modificado

2023-07-20 07:03 UTC, kevinmamaqi requested changes

2023-07-20 07:03 UTC, kevinmamaqi commented on front/src/components/organisms/Login.tsx
>        const response = await fetch(urls.logIn, config)
Crear fetcher fuera y usar useQuery

2023-07-21 11:30 UTC, jordilop commented on front/src/components/organisms/Register.tsx
> +const ButtonStyled = styled(Button)<TButton>`
el button base solo tiene colores primary, secondary o outline. El estilo del button onSuccess es verde, por lo que al ser puntual, he creado un estilo directo en el componente.

2023-07-21 11:52 UTC, jordilop commented on front/src/components/organisms/Register.tsx
> +        setTimeout(() => {
Según diseño, onSuccess tiene que aparecer entre 1-2 segundos. 
Al realizar la petición he añadido un delay de medio segundo para que aparezca el spinner de loading.
Modificado todo para tratarlo en useMutation (onSuccess, onMutate)

2023-07-21 11:53 UTC, jordilop commented on front/src/components/organisms/Register.tsx
> +      setTimeout(() => {
Según diseño, onSuccess tiene que aparecer entre 1-2 segundos.
Al realizar la petición he añadido un delay de medio segundo para que aparezca el spinner de loading.
Modificado todo para tratarlo en useMutation (onSuccess, onMutate)

2023-07-21 11:54 UTC, jordilop commented on front/src/components/organisms/Login.tsx
> +const ButtonStyled = styled(Button)<TButton>`
el button base solo tiene colores primary, secondary o outline. El estilo del button onSuccess es verde, por lo que al ser puntual, he creado un estilo directo en el componente.

2023-07-21 11:55 UTC, jordilop commented on front/src/components/organisms/Login.tsx
> +const StyledSpinner = styled(Spinner)`
Actualmente no hay un spinner que pueda modificar el tamaño o con un estilo definido

2023-07-24 22:52 UTC, jordilop commented
Realizadas todas las modificaciones. Los test no me salen.

2023-07-25 08:27 UTC, merged