389 fe edit my resources
IT-Academy-BCN/ita-wiki pull request #425
Opened 2023-07-17 18:38 UTC by missvader

2023-07-17 19:48 UTC, kevinmamaqi requested changes

2023-07-17 19:48 UTC, kevinmamaqi commented on front/src/__tests__/organisms/EditResource.test.tsx
> +import { fireEvent, render, screen } from '@testing-library/react'
Ya hay un provider desde test-utils.tsx.

2023-07-17 19:48 UTC, kevinmamaqi commented on front/src/__tests__/organisms/EditResource.test.tsx
> +test('Renders EditResource when resource is editable', () => {
Faltan tests de éxito al enviar y error cuando falla.

2023-07-17 19:48 UTC, kevinmamaqi commented on front/src/components/organisms/CardResourceLink.tsx
> +// eslint-disable-next-line import/no-cycle
Evitar cycle e importar desde el componente en que se usa.

2023-07-17 19:48 UTC, kevinmamaqi commented on front/src/components/organisms/EditResource.tsx
> +// eslint-disable-next-line import/no-cycle
Mismo

2023-07-17 19:48 UTC, kevinmamaqi commented on front/src/components/organisms/ResourceForm.tsx
> +      onSubmit={initialValues ? onSubmitUpdate : onSubmit}
Lo llamaría create y update.

2023-07-18 07:03 UTC, kevinmamaqi requested changes

2023-07-18 07:03 UTC, kevinmamaqi commented on front/src/components/organisms/EditResource.tsx
> +import { Modal } from '../molecules'
```suggestion
import { Modal } from '../molecules/Modal'
```

2023-07-18 11:01 UTC, missvader commented on front/src/__tests__/organisms/EditResource.test.tsx
> +test('Renders EditResource when resource is editable', () => {
esos tests ya estan en ResourceForm.test

2023-07-18 11:02 UTC, missvader commented on front/src/components/organisms/CardResourceLink.tsx
> +// eslint-disable-next-line import/no-cycle
Solucionado, de paso he eliminado el resto cycles revisando todos los componentes

2023-07-18 11:12 UTC, kevinmamaqi approved these changes

2023-07-19 07:06 UTC, kevinmamaqi approved these changes

2023-07-19 07:09 UTC, merged