451 add remove favourite resource by user endpoint
IT-Academy-BCN/ita-wiki pull request #477
Opened 2023-09-18 10:18 UTC by David-oss6

error en test numero 2 si ejecuto los 3 tests a la vez.
sin errores si los ejecuto 1 por 1

2023-09-18 11:13 UTC, kevinmamaqi-90poe requested changes

2023-09-18 11:13 UTC, kevinmamaqi-90poe commented on .gitignore
> +openapi.yami
Porqué?

2023-09-18 11:19 UTC, kevinmamaqi requested changes

2023-09-18 11:19 UTC, kevinmamaqi commented on .gitignore
> +openapi.yami
Por qué?

2023-09-19 08:59 UTC, kevinmamaqi approved these changes

2023-09-19 09:03 UTC, merged