487-be-bug-fix-get-favorite-resources-by-user-endpoint
IT-Academy-BCN/ita-wiki pull request #488
Opened 2023-09-20 18:21 UTC by xpan1c

2023-09-20 18:29 UTC, kevinmamaqi requested changes

2023-09-20 18:29 UTC, kevinmamaqi commented on back/src/__tests__/resources/favorites.test.ts
> +    expect(response.status).toBe(401)
El nombre del test dice 405

2023-09-26 11:15 UTC, alex0rpi commented on back/openapi.yaml
Esto es un comentario de prueba

2023-09-27 08:56 UTC, alex0rpi approved these changes

2023-09-28 06:55 UTC, SergiFont approved these changes

2023-09-28 07:54 UTC, kevinmamaqi approved these changes

2023-09-28 07:54 UTC, merged