470-fe-add-favorites-option-to-resource-card
IT-Academy-BCN/ita-wiki pull request #531
Opened 2023-10-08 14:56 UTC by NataliaR-BCN

2023-10-08 18:10 UTC, JuditKaramazov approved these changes
Amazing job!

2023-10-09 07:19 UTC, kevinmamaqi requested changes

2023-10-09 07:19 UTC, kevinmamaqi commented on front/src/components/molecules/FavoritesWidget.tsx
> +import { useEffect, useState } from 'react'
Renombrar a FavoritesIcon/FavoritesHeart...

2023-10-09 07:19 UTC, kevinmamaqi commented on front/src/components/organisms/MyFavoritesList.tsx
> +  const favoritesData = { data }.data as TFavorites[] | undefined
Eliminar linea

2023-10-09 07:19 UTC, kevinmamaqi commented on front/src/components/organisms/MyFavoritesList.tsx
> +  const { isLoading, isError, data } = useGetFavorites(slug)
```suggestion
  const { isLoading, isError, data: favoritesData } = useGetFavorites(slug)
```

2023-10-09 07:19 UTC, kevinmamaqi commented on front/src/components/organisms/MyFavoritesList.tsx
> +        (favoritesData && favoritesData.length > 0 ? (
favoritesData?.length ? ...

2023-10-09 10:28 UTC, NataliaR-BCN commented on front/src/components/organisms/MyFavoritesList.tsx
> +  const { isLoading, isError, data } = useGetFavorites(slug)
Also fixed in UserProfile.tsx

2023-10-10 10:10 UTC, NataliaR-BCN commented on front/src/components/organisms/MyFavoritesList.tsx
> +        (favoritesData && favoritesData.length > 0 ? (
{data && 
        (data?.length > 0 ?
        ...

2023-10-16 12:25 UTC, JuditKaramazov approved these changes

2023-10-16 12:31 UTC, kevinmamaqi approved these changes

2023-10-16 14:30 UTC, merged