524-handle-text-overflow-in-resource-cards-for-small-screens
IT-Academy-BCN/ita-wiki pull request #543
Opened 2023-10-12 08:55 UTC by Xerxi88

2023-10-12 09:05 UTC, Xerxi88 commented
After: 
![image](https://github.com/IT-Academy-BCN/ita-wiki/assets/107618143/e0823488-cc8e-40c5-bac1-818b11afc545)
![image](https://github.com/IT-Academy-BCN/ita-wiki/assets/107618143/999126b1-29d2-4cba-865c-233ed8f34730)


Before: 
![image](https://github.com/IT-Academy-BCN/ita-wiki/assets/107618143/3d73c04c-cb87-4651-b3b4-1e16caee91ec)
![image](https://github.com/IT-Academy-BCN/ita-wiki/assets/107618143/d006460b-f3c7-4adb-95dc-e574e870fd14)

2023-10-12 11:55 UTC, NataliaR-BCN reviewed
Sorry, but I think this does not solve the overflow of long texts in the Resource Card on small screens. 
Contact me on Discord if you need any help, please.
![errorResourceCard](https://github.com/IT-Academy-BCN/ita-wiki/assets/92027716/3951b7b7-865d-4710-8801-5d60f00b9acf)

2023-10-16 07:05 UTC, kevinmamaqi requested changes

2023-10-16 07:05 UTC, kevinmamaqi commented on front/src/components/organisms/Navbar.tsx
> +  @media (max-width: 480px) {
Utilizar estilos de device.Mobile/Tablet, etc...

2023-10-17 12:25 UTC, Xerxi88 commented on front/src/components/molecules/SelectLanguage.tsx
> +       color: ${colors.gray.gray3};
none, the tabulation may be reflected

2023-10-17 12:26 UTC, Xerxi88 commented on front/src/components/organisms/Navbar.tsx
> +    background-color: ${colors.black};
Yes, the correct color would be "black.black3" for example, finally I change it to "gray.gray5" to correctly follow the design.

2023-10-18 06:58 UTC, NataliaR-BCN approved these changes

2023-10-18 07:44 UTC, kevinmamaqi approved these changes

2023-10-18 07:48 UTC, merged