499-be-bug-seen-and-not-seen-not-implemented-not-working-properly
IT-Academy-BCN/ita-wiki pull request #554
Opened 2023-10-17 09:52 UTC by xpan1c

- Removed status from zod and Prisma schemas
- Added POST /seen/:resourceId
- Updated GET /resources controller
- Added param zod schema

2023-10-17 10:09 UTC, kevinmamaqi requested changes

2023-10-17 10:09 UTC, kevinmamaqi commented on back/src/__tests__/resources/get.test.ts
> +  it('should get viewed resources with status SEEN when logged in', async () => {
It should get all resources, without status in the response when not logged in

2023-10-17 10:09 UTC, kevinmamaqi commented on back/src/__tests__/resources/get.test.ts
> +  it('should get all resources with status NOT_SEEN when not logged in', async () => {
It should get all resources, without status in the response when not logged in

2023-10-17 10:09 UTC, kevinmamaqi commented on back/src/__tests__/resources/get.test.ts
> +  it('should get all resources with status NOT_SEEN when logged in', async () => {
Aquí testear que filtra SEEN/NOT_SEEN

2023-10-17 10:09 UTC, kevinmamaqi commented on back/src/__tests__/resources/get.test.ts
> +  it('should get all resources with status NOT_SEEN when not logged in', async () => {
Cuando no esta logeado no hace falta el status

2023-10-18 07:43 UTC, kevinmamaqi requested changes

2023-10-18 07:43 UTC, kevinmamaqi commented on back/src/controllers/seen/create.ts
> +  const existingViewedResource = await prisma.viewedResource.findUnique({
use primsa upsert

2023-10-18 09:42 UTC, alex0rpi approved these changes

2023-10-18 15:36 UTC, kevinmamaqi approved these changes

2023-10-18 16:30 UTC, merged