Prevented voteCounter from making too many fetch vote requests
IT-Academy-BCN/ita-wiki pull request #555
Opened 2023-10-17 16:02 UTC by ViuCoding

2023-10-24 07:22 UTC, kevinmamaqi requested changes

2023-10-24 07:22 UTC, kevinmamaqi commented on front/src/components/molecules/VoteCounter.tsx
> +    switch (userVote) {
return {
downvote: getDownVote(vote, value)
}

const getDownVote(vote, value) {
  if (vote === 'up' && value === -1) return value + 1;
  if (vote === 'up' && ....
  if (

2023-10-25 17:17 UTC, JuditKaramazov submitted a review, later dismissed

2023-10-26 07:31 UTC, kevinmamaqi submitted a review, later dismissed

2023-10-26 08:39 UTC, missvader approved these changes

2023-10-26 08:53 UTC, kevinmamaqi approved these changes

2023-10-26 08:56 UTC, merged