551-fe-fix-mobile-styles
IT-Academy-BCN/ita-wiki pull request #558
Opened 2023-10-18 19:17 UTC by jenDevelopez

2023-10-19 07:13 UTC, kevinmamaqi requested changes
utilizar prettier

2023-10-19 07:13 UTC, kevinmamaqi commented on front/package.json
> +    "zod": "^3.22.4"
```suggestion
    "zod": "3.22.4"
```

2023-10-19 07:13 UTC, kevinmamaqi commented on front/src/components/molecules/CreateAuthor.tsx
> +
```suggestion
```

2023-10-25 20:04 UTC, JuditKaramazov approved these changes

2023-10-26 07:31 UTC, kevinmamaqi approved these changes

2023-10-26 07:38 UTC, closed without merging