533-fe-manage-users-modal
IT-Academy-BCN/ita-wiki pull request #568
Opened 2023-10-21 23:04 UTC by JuditKaramazov

**SettingsManager changes**:

- [x] It doesn't show the Usuaris tab if the user doesn't have enough permissions (role: mentor or higher).

- [x] Only admin roles can edit the users.

- [x] Tests have been updated accordingly.

2023-10-23 07:10 UTC, kevinmamaqi requested changes
Add `id` and `requiredRole`.

2023-10-23 07:10 UTC, kevinmamaqi commented on front/src/components/organisms/SettingsManager.tsx
> +      return true
```suggestion
      return false
```

2023-10-24 07:06 UTC, kevinmamaqi requested changes

2023-10-24 07:06 UTC, kevinmamaqi commented on front/src/components/organisms/SettingsManager.tsx
>  type TTabsData = {
Extender el type de Tabs.tsx para evitar duplicidades.

2023-10-31 08:06 UTC, kevinmamaqi approved these changes

2023-11-01 11:46 UTC, NataliaR-BCN commented on front/src/__tests__/organisms/SettingsManager.test.tsx
> -    ).toBeInTheDocument()
This text is still available, isn't it? 
Or what happens in the Temes tab if a Mentor/the Admin opens the SettingsManager from Home page, where there is not slug (needed to render topics)?

2023-11-01 11:48 UTC, NataliaR-BCN commented on front/src/__tests__/organisms/SettingsManager.test.tsx
> +    })
You're expecting a text that you already clicked

2023-11-01 11:48 UTC, NataliaR-BCN commented on front/src/__tests__/organisms/SettingsManager.test.tsx
> +    })
You're expecting a text that you already clicked

2023-11-01 11:51 UTC, NataliaR-BCN commented on front/src/__tests__/organisms/UsersManager.test.tsx
> +
'User Two' already expected 6 lines ago

2023-11-01 11:52 UTC, NataliaR-BCN commented on front/src/components/organisms/UsersManager.tsx
> +      Users Manager
Translate this text, please!

2023-11-06 08:03 UTC, kevinmamaqi approved these changes

2023-11-06 08:06 UTC, kevinmamaqi requested changes
Revisar tests y utilizar msw (mock service worker) y sus handlers.

2023-11-06 08:06 UTC, kevinmamaqi commented on front/src/__tests__/organisms/SettingsManager.test.tsx
> +  it('only allows admins to fetch users, and renders an error if the process fails', async () => {
Corregir test, ¿Como sabemos si el proceso falla?

2023-11-06 08:06 UTC, kevinmamaqi commented on front/src/__tests__/organisms/SettingsManager.test.tsx
> +  it('changes content tab according to click on menu tab', async () => {
No parece necesario que sea asincrono

2023-11-06 08:38 UTC, NataliaR-BCN commented
As AccountAdmin is now rendered from another component, maybe it should be in components instead of pages, and deleted from router in main

2023-11-09 06:26 UTC, kevinmamaqi approved these changes

2023-11-09 07:46 UTC, ViuCoding approved these changes

2023-11-09 07:50 UTC, merged