546 fe move all fetchs to react query hooks
IT-Academy-BCN/ita-wiki pull request #573
Opened 2023-10-24 13:16 UTC by missvader

also clean types

2023-10-24 17:30 UTC, NataliaR-BCN submitted a review, later dismissed

2023-10-24 20:18 UTC, JuditKaramazov submitted a review, later dismissed

2023-10-25 07:07 UTC, kevinmamaqi requested changes

2023-10-25 07:07 UTC, kevinmamaqi commented on front/src/components/atoms/Button.tsx
> -type TButton = ButtonHTMLAttributes<HTMLButtonElement> & {
Restaurar types de atoms/molecules

2023-10-25 07:12 UTC, kevinmamaqi requested changes

2023-10-25 07:12 UTC, kevinmamaqi commented on front/src/__tests__/hooks/useGetCategories.test.tsx
> +  beforeEach(() => {
Probar con msw, ejemplo: https://github.com/IT-Academy-BCN/ita-wiki/blob/main/front/src/__tests__/hooks/useGetTopics.test.tsx

2023-10-26 07:28 UTC, kevinmamaqi approved these changes

2023-10-26 07:29 UTC, JuditKaramazov approved these changes

2023-10-26 07:29 UTC, NataliaR-BCN approved these changes

2023-10-26 07:31 UTC, merged