reemplazo del login y arreglo de Userschema
IT-Academy-BCN/ita-wiki pull request #58
Opened 2023-03-23 11:25 UTC by ivanlegranbizarro

2023-03-23 11:32 UTC, ivanlegranbizarro commented
En principio, además del controlador y la ruta del login, he arreglado también las validaciones de Zod con aquello de pick/omit que has comentado en el daily, creando un middleware en el que se modifica el UserSchema para que solo haga pick de dni y password.

2023-03-23 11:32 UTC, kevinmamaqi requested changes

2023-03-23 11:32 UTC, kevinmamaqi commented on back/src/controllers/loginController.ts
> +    throw ValidationError
Esta bien la sintaxis?

2023-03-23 11:32 UTC, kevinmamaqi commented on back/src/controllers/loginController.ts
> +  const token = jwt.sign({ userId: user.id }, process.env.JWT_SECRET as Secret);
Faltaria definiry el expiry

2023-03-23 11:32 UTC, kevinmamaqi commented on back/src/middleware/validationMiddleware.ts
> +export const validateLoginData = async (ctx: Koa.Context, next: Koa.Next) => {
Ya hay un middleware de validate, y uno de parse, que se pueden usar en el router pasandoles el schema.

2023-03-23 11:32 UTC, kevinmamaqi commented on back/src/routes/loginRouter.ts
> +import Router from '@koa/router';
me parecia bien tener el auth router con login, register, ...

2023-03-23 11:32 UTC, kevinmamaqi commented on back/src/routes/loginRouter.ts
> +import { loginController } from '../controllers/loginController';
Que se importe de '../controllers', no el subnivel

2023-03-23 11:33 UTC, ivanlegranbizarro commented on back/src/controllers/loginController.ts
> +  const token = jwt.sign({ userId: user.id }, process.env.JWT_SECRET as Secret);
Guay, gracias. Voy!

2023-03-23 11:41 UTC, ivanlegranbizarro commented on back/src/controllers/loginController.ts
> +    throw ValidationError
En teoría sí. bcrypt tiene un método compare al que hay que pasarle los dos datos, no? O no me hablas de eso?

2023-03-23 11:46 UTC, ivanlegranbizarro commented on back/src/routes/loginRouter.ts
> +import Router from '@koa/router';
De acuerdo. Corregido para que ambos estén en authRoutes.

2023-03-23 11:48 UTC, ivanlegranbizarro commented on back/src/routes/loginRouter.ts
> +import { loginController } from '../controllers/loginController';
Aquí no te entiendo. Se autoimporta así. Qué cambio quieres exactamente que haga?

2023-03-23 15:05 UTC, kevinmamaqi requested changes

2023-03-23 15:05 UTC, kevinmamaqi commented on back/src/controllers/loginController.ts
> +  const { dni, password } = ctx.request.body;
Todo esto debería estar en un try,catch

2023-03-23 15:05 UTC, kevinmamaqi commented on back/src/routes/authRouter.ts
> +  async (ctx: Koa.Context) => {
¿Por qué no la ruta final?

2023-03-23 15:05 UTC, kevinmamaqi commented on back/src/schemas/UserLoginSchema.ts
> +
Hueco extra innecesario

2023-03-23 15:05 UTC, kevinmamaqi commented on back/src/server.ts
> -import * as Routes from './routes'
Dejalo como estaba, es un cambio innecesario en esta PR, solo hace dificil medir el alcance

2023-03-24 07:57 UTC, ivanlegranbizarro commented on back/src/routes/loginRouter.ts
> +import { loginController } from '../controllers/loginController';
Arreglado, gracias. No sabía ni cómo se hacía eso  xD (nunca había usado esta manera tan guay de enrutar)

2023-03-24 07:59 UTC, ivanlegranbizarro commented on back/src/controllers/loginController.ts
> +  const { dni, password } = ctx.request.body;
Hecho!

2023-03-24 07:59 UTC, ivanlegranbizarro commented on back/src/routes/authRouter.ts
> +  async (ctx: Koa.Context) => {
Hecho

2023-03-24 08:01 UTC, ivanlegranbizarro commented on back/src/server.ts
> -import * as Routes from './routes'
Hecho

2023-03-24 08:18 UTC, ivanlegranbizarro commented on back/src/controllers/loginController.ts
> +  ctx.body = { token };
Corregido!

2023-03-27 07:06 UTC, kevinmamaqi requested changes
Falta test

2023-03-27 18:58 UTC, kevinmamaqi requested changes

2023-03-27 18:58 UTC, kevinmamaqi commented on back/src/__tests__/auth/login.test.ts
> +  expect(response.status).toBe(204)
Checkea los headers

2023-03-27 18:58 UTC, kevinmamaqi commented on back/src/__tests__/auth/login.test.ts
> +test('/api/v1/auth/login', async () => {
El nombre del test es importante, dale un nombre semantico e incluye cada test en un describe.

2023-03-27 18:58 UTC, kevinmamaqi commented on back/src/__tests__/auth/login.test.ts
> +test('/api/v1/auth/login', async () => {
El nombre del test es importante, dale un nombre semantico e incluye cada test en un describe.

2023-03-27 18:58 UTC, kevinmamaqi commented on back/src/__tests__/auth/login.test.ts
> +  expect(response.status).toBe(400)
Checkea el mensaje de error que envias, debeía de haber para email/contraseña, etc... en función del error.

2023-03-28 20:22 UTC, kevinmamaqi approved these changes

2023-03-29 06:35 UTC, merged