561 implement filters context
IT-Academy-BCN/ita-wiki pull request #582
Opened 2023-10-29 17:38 UTC by Lahali

2023-11-08 17:03 UTC, Xerxi88 submitted a review, later dismissed

2023-11-08 18:42 UTC, JuditKaramazov approved these changes

2023-11-09 06:28 UTC, kevinmamaqi requested changes
Sobra todo lo de back, el compose y .github/workflows y el packages/schema. Has mergeado un issue abierto, no main.

2023-11-09 06:28 UTC, kevinmamaqi commented on .github/workflows/back-deploy-dev.yml
> +          pm2 start --name server-dev dist/server.js
```suggestion
          pm2 start --name server-dev dist/src/server.js 
```

2023-11-09 22:31 UTC, JuditKaramazov approved these changes

2024-02-06 09:00 UTC, closed without merging