586 send post request with seen resource when clicked on the title and logged in
IT-Academy-BCN/ita-wiki pull request #600
Opened 2023-11-01 14:56 UTC by ViuCoding

2023-11-06 07:54 UTC, JuditKaramazov submitted a review, later dismissed

2023-11-06 08:09 UTC, kevinmamaqi requested changes

2023-11-06 08:09 UTC, kevinmamaqi commented on front/src/__tests__/molecules/ResourceTitleLink.test.tsx
> +const renderWithQueryClient = (component: React.ReactNode) =>
El render que usamos ya tiene el provider, no es necesario añadirlo de nuevo.

2023-11-06 08:09 UTC, kevinmamaqi commented on front/src/__tests__/molecules/ResourceTitleLink.test.tsx
> +  it('should open the link in a new browser tab', async () => {
Comprobar que se envía la petición al hacer clic en el enlace

2023-11-07 16:36 UTC, NataliaR-BCN approved these changes

2023-11-07 19:46 UTC, JuditKaramazov approved these changes

2023-11-08 08:09 UTC, kevinmamaqi approved these changes

2023-11-08 08:09 UTC, merged