#587 new resource search bar UI implementation
IT-Academy-BCN/ita-wiki pull request #639
Opened 2023-11-16 14:32 UTC by Xerxi88

2023-11-18 13:30 UTC, JuditKaramazov approved these changes

2023-11-19 12:20 UTC, NataliaR-BCN requested changes
Please, translate the added texts.
And maybe consider refactoring the code into a separate component.

2023-11-20 23:41 UTC, JuditKaramazov requested changes

2023-11-20 23:41 UTC, JuditKaramazov commented on front/src/pages/Category.tsx
> +                <VotesDateContainer>
Great job so far! However, I noticed that the recent changes introducing 'VotesDateController' were reverted, and 'VotesDateContainer' is back in use. Please note that 'VotesDateController' contains all the previous logic and styles while staying as an isolated component now!

2023-11-21 08:35 UTC, kevinmamaqi requested changes

2023-11-21 08:35 UTC, kevinmamaqi commented on front/CHANGELOG.md
> +## [0.3.1] - 2023-11-16
```suggestion
## [0.3.0] - 2023-11-16
```

2023-11-21 08:35 UTC, kevinmamaqi commented on front/package.json
> +  "version": "0.3.1",
```suggestion
  "version": "0.3.0",
```

2023-11-22 10:43 UTC, closed without merging