53 add register form
IT-Academy-BCN/ita-wiki pull request #70
Opened 2023-03-29 06:47 UTC by Lahali

2023-04-11 07:19 UTC, kevinmamaqi requested changes

2023-04-11 07:19 UTC, kevinmamaqi commented on front/src/__mocks__/handlers.ts
> +      ctx.json([
Respuesta vacia, actualizad back @guillempado @ivanlegranbizarro

2023-04-11 07:19 UTC, kevinmamaqi commented on front/src/__tests__/pages/Register.test.tsx
> +    expect(response.data).toEqual([
Comprobar estado cuando back este listo, 204

2023-04-11 07:19 UTC, kevinmamaqi commented on front/src/pages/Register.tsx
> +            error={errors.confirmPassword && true}
errors.confirmPassword?.message

2023-04-11 07:19 UTC, kevinmamaqi commented on front/src/pages/Register.tsx
> +            validationMessage={
Pasar la validación al resolver

2023-04-11 07:19 UTC, kevinmamaqi commented on front/src/pages/Register.tsx
> +const UserRegisterSchema = z.object({
Todas las validaciones y mensajes de error deben estar aquí

2023-04-11 07:19 UTC, kevinmamaqi commented on front/src/pages/Register.tsx
> +          <InputGroup
required como parametro

2023-04-11 11:26 UTC, Lahali commented on front/package.json
> +    "react-axios": "^2.0.6",
Hecho

2023-04-11 16:40 UTC, Lahali commented on front/package.json
> +    "react-axios": "^2.0.6",
Hecho!

2023-04-11 16:40 UTC, Lahali commented on front/src/__mocks__/handlers.ts
> +      ctx.status(200),
Hecho

2023-04-11 16:40 UTC, Lahali commented on front/src/__mocks__/handlers.ts
> +      ctx.json([
Hecho

2023-04-11 16:41 UTC, Lahali commented on front/src/pages/Register.tsx
> +            validationMessage={
Hecho

2023-04-11 16:44 UTC, Lahali commented on front/src/pages/Register.tsx
> +          <InputGroup
Hecho

2023-04-12 07:40 UTC, kevinmamaqi approved these changes

2023-04-12 07:41 UTC, merged