[BE] Add registration endpoint [route + logic] (#38)
IT-Academy-BCN/ita-wiki pull request #71
Opened 2023-03-29 15:17 UTC by guillempado

Develops #38 
Closes #68  

Pending issues:
- [ ] Zod route validation middleware returns non descriptive error messages

<img width="845" alt="image" src="https://user-images.githubusercontent.com/28660385/228584364-1440adb8-8387-4761-9cf0-426dd909b44b.png">

2023-03-29 15:52 UTC, kevinmamaqi requested changes

2023-03-29 15:52 UTC, kevinmamaqi commented on back/.gitignore
> +prisma/migrations/*
Las migraciones tienen que estar en el repo

2023-03-29 16:00 UTC, kevinmamaqi requested changes

2023-03-29 16:00 UTC, kevinmamaqi commented on back/src/controllers/registerController.ts
> +  } catch (error) {
El try catch sobra porque tenemos un error middleware para esto. Los errores también estan normalizados.

2023-03-29 17:20 UTC, kevinmamaqi requested changes

2023-03-29 17:20 UTC, kevinmamaqi commented on back/package.json
> +    "test": "npm run prisma:migrate:reset && vitest",
Esto tiene que quedar como estaba.

2023-03-30 09:10 UTC, guillempado commented
Mejoras en el mensaje de error de Zod, pero no entiendo porqué no lo parsea bien.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/28660385/228786935-452a049f-c39d-42de-9072-c982213f871a.png">

2023-03-30 14:06 UTC, guillempado commented
- [x] Fixed parsing in Zod validation response

<img width="848" alt="image" src="https://user-images.githubusercontent.com/28660385/228861605-39bbc64a-6f15-4616-b09e-c2948617e9bf.png">

2023-04-11 07:24 UTC, kevinmamaqi requested changes

2023-04-11 07:24 UTC, kevinmamaqi commented on back/src/controllers/loginController.ts
> +    ctx.status = 401
404

2023-04-11 07:24 UTC, kevinmamaqi commented on back/src/controllers/loginController.ts
> +    ctx.status = 401
422: https://stackoverflow.com/questions/3050518/what-http-status-response-code-should-i-use-if-the-request-is-missing-a-required

2023-04-11 08:16 UTC, kevinmamaqi submitted a review, later dismissed

2023-04-11 08:30 UTC, kevinmamaqi approved these changes

2023-04-11 09:47 UTC, merged