726-febug-fix-filter-applied-when-clicking-on-newresource-radiobutton
IT-Academy-BCN/ita-wiki pull request #727
Opened 2023-11-28 19:51 UTC by octapf

- [x] Generate unique ID for linking label with HTML Element

2023-11-29 08:22 UTC, kevinmamaqi requested changes

2023-11-29 08:22 UTC, kevinmamaqi commented on front/src/components/atoms/Radio.tsx
> +          <FlexBox direction="row" key={id}>
Change id in the parent component

2023-11-29 08:22 UTC, kevinmamaqi commented on front/src/components/atoms/Radio.tsx
> +        const randomID = Math.round(Math.random() * 10000)
Delete

2024-01-10 15:09 UTC, kevinmamaqi approved these changes

2024-01-10 16:59 UTC, missvader approved these changes

2024-01-10 17:17 UTC, NataliaR-BCN commented on front/src/components/atoms/CheckBox.tsx
> -  ) => (
The id as a prop is now unnecessary, then?

2024-01-11 10:45 UTC, merged