753-fe-migrate-input-atom-to-storybook
IT-Academy-BCN/ita-wiki pull request #759
Opened 2023-12-13 14:19 UTC by missvader

2023-12-14 08:26 UTC, NataliaR-BCN approved these changes

2023-12-14 08:31 UTC, JuditKaramazov submitted a review, later dismissed

2023-12-18 17:59 UTC, Xerxi88 approved these changes

2023-12-18 18:26 UTC, NataliaR-BCN approved these changes

2023-12-18 18:30 UTC, JuditKaramazov submitted a review, later dismissed

2023-12-18 20:07 UTC, kevinmamaqi requested changes

2023-12-18 20:07 UTC, kevinmamaqi commented on packages/ui/package.json
> +    "react-router-dom": "6.9.0"
Esto fuera

2023-12-19 08:00 UTC, NataliaR-BCN submitted a review, later dismissed

2023-12-19 08:05 UTC, Xerxi88 approved these changes

2023-12-19 08:06 UTC, Xerxi88 approved these changes

2023-12-19 08:16 UTC, JuditKaramazov submitted a review, later dismissed

2023-12-21 08:57 UTC, merged