809 fe sso create the initial structure of sso front
IT-Academy-BCN/ita-wiki pull request #813
Opened 2024-01-11 13:52 UTC by marmorrei

Closes #809

2024-01-11 16:39 UTC, missvader requested changes
Some folders better not include them in initial structure. We have to consider that it's a different app from ITA-wiki, and it's possible that they may not be needed.

2024-01-11 16:39 UTC, missvader commented on sso_front/index.html
> +  <title>ITA Wiki</title>
Change title to ITA-SSO for now

2024-01-11 16:39 UTC, missvader commented on sso_front/src/context/.gitkeep
Remove folder

2024-01-11 16:39 UTC, missvader commented on sso_front/src/locales/.gitkeep
Remove folder

2024-01-11 16:39 UTC, missvader commented on config/dev/ui.yml
This changes are from UI, remove them

2024-01-12 08:12 UTC, marmorrei commented on config/dev/ui.yml
Ok, I am not sure how this ended up here! I will check.

2024-01-12 10:59 UTC, missvader approved these changes

2024-01-12 11:00 UTC, merged