778 fe migrate radio
IT-Academy-BCN/ita-wiki pull request #823
Opened 2024-01-17 07:48 UTC by marmorrei

Closes #778

2024-01-17 08:05 UTC, kevinmamaqi requested changes

2024-01-17 08:05 UTC, kevinmamaqi commented on packages/ui/src/__tests__/atoms/Radio.test.tsx
> +// describe('Radio', () => {
Eliminar

2024-01-17 08:05 UTC, kevinmamaqi commented on packages/ui/src/components/atoms/Radio.tsx
> +export default styled(Radio)``
Export named component, not default styled

2024-01-17 10:07 UTC, NataliaR-BCN submitted a review, later dismissed

2024-01-18 08:30 UTC, kevinmamaqi approved these changes

2024-01-18 08:33 UTC, NataliaR-BCN approved these changes

2024-01-18 08:34 UTC, merged