Migrate AccessModalContent to package UI
IT-Academy-BCN/ita-wiki pull request #921
Opened 2024-02-03 07:15 UTC by octapf

Close #920

2024-02-03 10:28 UTC, REALcuba submitted a review, later dismissed

2024-02-03 11:25 UTC, NataliaR-BCN commented on packages/ui/src/__tests__/molecules/AccessModalContent.test.tsx
> +import { fireEvent, render, screen, waitFor } from '../test-utils'
Or import directly from '@testing-library/react'

2024-02-05 08:21 UTC, kevinmamaqi requested changes

2024-02-05 08:21 UTC, kevinmamaqi commented on packages/ui/src/stories/molecules/AccessModalContent.stories.ts
> +import customImg from '../assets/lock-dynamic-color.svg'
Pass as props

2024-02-05 08:21 UTC, kevinmamaqi commented on packages/ui/src/components/molecules/AccessModalContent.tsx
> +  svgSrc: string
img

type TImg {
src: string
alt: string
}

2024-02-05 08:21 UTC, kevinmamaqi commented on packages/ui/src/stories/molecules/AccessModalContent.stories.ts
> +import type { Meta, StoryObj } from '@storybook/react'
Crear carpeta `AccessModalContent/index.tsx`

2024-02-05 08:55 UTC, kevinmamaqi submitted a review, later dismissed

2024-02-05 08:56 UTC, NataliaR-BCN approved these changes

2024-02-05 09:33 UTC, NataliaR-BCN approved these changes

2024-02-05 10:25 UTC, marmorrei approved these changes

2024-02-05 10:37 UTC, merged